#!/usr/bin/env python3
"""Pure Q4 schema contract for B3 evidence spans; no executable apply surface."""

from __future__ import annotations

import hashlib
import json
from typing import Any, Mapping, Sequence

SCHEMA_VERSION = "kg-stage3-b3-span-schema/2.0"
TABLE = "evidence_spans"
COORDINATE_SYSTEM = "unicode_codepoint_half_open"
SPAN_KINDS = ("stage1_meeting_event", "stage3_result_item")

CREATE_TABLE = f"""CREATE TABLE {TABLE} (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supporting_doc_id integer NOT NULL,
    span_kind varchar(32) NOT NULL,
    coordinate_system varchar(40) NOT NULL,
    text_offset_start integer NOT NULL,
    text_offset_end integer NOT NULL,
    span_sha256 char(64) NOT NULL,
    evidence_content_sha256 char(64) NOT NULL,
    extraction_method varchar(512) NOT NULL,
    extractor_version varchar(128) NOT NULL,
    agenda_item_db_id integer NOT NULL,
    meeting_event_id integer NULL,
    result_document_id integer NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT uq_evidence_spans_identity UNIQUE
      (supporting_doc_id, span_kind, text_offset_start, text_offset_end),
    CONSTRAINT ck_evidence_spans_offsets CHECK
      (text_offset_start >= 0 AND text_offset_end > text_offset_start),
    CONSTRAINT ck_evidence_spans_coordinate CHECK
      (coordinate_system = '{COORDINATE_SYSTEM}'),
    CONSTRAINT ck_evidence_spans_kind CHECK
      (span_kind IN ('stage1_meeting_event', 'stage3_result_item')),
    CONSTRAINT ck_evidence_spans_hashes CHECK
      (span_sha256 ~ '^[0-9a-f]{{64}}$'
       AND evidence_content_sha256 ~ '^[0-9a-f]{{64}}$'),
    CONSTRAINT ck_evidence_spans_extractor CHECK
      (length(btrim(extraction_method)) > 0 AND length(btrim(extractor_version)) > 0),
    CONSTRAINT ck_evidence_spans_lineage CHECK (
      (span_kind = 'stage1_meeting_event' AND meeting_event_id IS NOT NULL
       AND result_document_id IS NULL)
      OR
      (span_kind = 'stage3_result_item' AND meeting_event_id IS NULL
       AND result_document_id = supporting_doc_id)
    ),
    CONSTRAINT fk_evidence_spans_document FOREIGN KEY (supporting_doc_id)
      REFERENCES supporting_documents(id) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_evidence_spans_item FOREIGN KEY (agenda_item_db_id)
      REFERENCES agenda_items(id) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_evidence_spans_event FOREIGN KEY (meeting_event_id)
      REFERENCES meeting_events(id) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_evidence_spans_result_document FOREIGN KEY (result_document_id)
      REFERENCES supporting_documents(id) ON DELETE RESTRICT ON UPDATE CASCADE
)"""

DDL = (
    CREATE_TABLE,
    f"CREATE INDEX ix_{TABLE}_agenda_item_db_id ON {TABLE} (agenda_item_db_id)",
    f"CREATE INDEX ix_{TABLE}_meeting_event_id ON {TABLE} (meeting_event_id) "
    "WHERE meeting_event_id IS NOT NULL",
    f"CREATE INDEX ix_{TABLE}_result_document_id ON {TABLE} (result_document_id) "
    "WHERE result_document_id IS NOT NULL",
)


def canonical_sha256(value: Any) -> str:
    return hashlib.sha256(json.dumps(
        value, sort_keys=True, separators=(",", ":"), default=str
    ).encode("utf-8")).hexdigest()


def schema_contract() -> dict[str, Any]:
    body = {
        "version": SCHEMA_VERSION, "table": TABLE,
        "coordinate_system": COORDINATE_SYSTEM, "span_kinds": list(SPAN_KINDS),
        "ddl": list(DDL), "ddl_count": len(DDL),
        "identity": ["supporting_doc_id", "span_kind", "text_offset_start",
                     "text_offset_end"],
        "evidence_version": ["supporting_doc_id", "evidence_content_sha256",
                             "extraction_method", "extractor_version"],
        "lineage": {
            "stage1_meeting_event": "meeting_event_id -> meeting_events.id",
            "stage3_result_item": "result_document_id -> supporting_documents.id; "
                                  "result_document_id = supporting_doc_id",
            "exactly_one_parent": True,
        },
        "canonical_item_required": True, "on_delete": "RESTRICT",
    }
    return {**body, "digest": canonical_sha256(body)}


def validate_schema_contract(value: Mapping[str, Any]) -> list[str]:
    problems: list[str] = []
    if dict(value) != schema_contract():
        problems.append("schema contract differs from the canonical Q4 contract")
    ddl = "\n".join(value.get("ddl") or [])
    required = (
        "evidence_content_sha256", "extraction_method", "extractor_version",
        "span_sha256 ~ '^[0-9a-f]{64}$'", "length(btrim(extraction_method)) > 0",
        "agenda_item_db_id integer NOT NULL", "meeting_event_id integer NULL",
        "result_document_id integer NULL", "result_document_id = supporting_doc_id",
        "REFERENCES supporting_documents(id) ON DELETE RESTRICT",
        "REFERENCES agenda_items(id) ON DELETE RESTRICT",
        "REFERENCES meeting_events(id) ON DELETE RESTRICT",
    )
    for fragment in required:
        if fragment not in ddl:
            problems.append(f"schema omits required fragment: {fragment}")
    if value.get("coordinate_system") != COORDINATE_SYSTEM:
        problems.append("schema uses the wrong coordinate system")
    return problems


def validate_schema_preimage(*, present_tables: Sequence[str],
                             expected_schema_sha256: str,
                             current_schema_sha256: str) -> list[str]:
    problems: list[str] = []
    if TABLE in set(present_tables):
        problems.append(f"{TABLE} already exists; create-plan preimage is stale")
    if not expected_schema_sha256 or expected_schema_sha256 != current_schema_sha256:
        problems.append("bound source schema differs from current schema")
    return problems
