#!/usr/bin/env python3
"""Row mapping and current-state derivation for the receipt store (design-only).

The store has exactly one writer-supplied column: the canonical ``receipt_body``.
Everything else is generated by the database from that body, so these pure functions
mirror what the database will derive and let the design be attacked offline:

* ``typed_row`` maps one terminal action to the single-column insert it may perform;
* ``derived_columns`` reproduces the generated columns so their rules can be checked;
* ``plan_appends`` decides which inserts would happen, refusing duplicates, unresolved
  stored conflicts, older or equal-instant arrivals, and more than one action per
  identity in a single call.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from typing import Any, Mapping, Sequence

from scripts.kg import stage3_processing_receipt as receipt
from scripts.kg import stage3_processing_receipt_store_schema as schema

CONFLICT_STATUS = "conflict"
STORE_ASSIGNED_COLUMNS = ("receipt_id", "inserted_at")
WRITER_SUPPLIED_COLUMNS = ("receipt_body",)
GENERATED_COLUMNS = tuple(schema.DERIVED_FROM_BODY)


class StoreRefused(RuntimeError):
    """A store rule refused the request."""


def _iso(value: Any) -> str | None:
    try:
        if isinstance(value, datetime):
            return value.astimezone(timezone.utc).isoformat()
        parsed = datetime.fromisoformat(str(value).replace("Z", "+00:00"))
    except (TypeError, ValueError):
        return None
    if parsed.tzinfo is None:
        parsed = parsed.replace(tzinfo=timezone.utc)
    return parsed.astimezone(timezone.utc).isoformat()


def _recorded_at_sort_key(value: Any) -> int | None:
    """Mirror the schema's immutable UTC-microsecond ordering key."""
    normalized = _iso(value)
    if normalized is None:
        return None
    instant = datetime.fromisoformat(normalized)
    delta = instant - datetime(1970, 1, 1, tzinfo=timezone.utc)
    return (delta.days * 86400 + delta.seconds) * 1_000_000 + delta.microseconds


def derived_columns(body: Mapping[str, Any]) -> dict[str, Any]:
    """Exactly the columns the database generates from ``body``."""
    identity = list(body.get("processing_identity") or [])
    acquisition = body.get("acquisition") or {}
    padded = identity + [None] * (6 - len(identity))
    return {
        "source_kind": padded[0],
        "source_id": padded[1],
        "content_sha256": padded[2],
        "extraction_method": padded[3],
        "extractor": padded[4],
        "extractor_version": padded[5],
        "producer_version": body.get("producer_version"),
        "receipt_digest": body.get("digest"),
        "status": body.get("status"),
        "reason": str(body.get("reason") or ""),
        "recorded_at": body.get("recorded_at"),
        "recorded_at_sort_key": _recorded_at_sort_key(body.get("recorded_at")),
        "acquisition_class": acquisition.get("class"),
        "legacy_swept_at_present": bool(acquisition.get("legacy_swept_at_present")),
        "does_not_prove_processing": acquisition.get("does_not_prove_processing") is True,
    }


def identity_components(body: Mapping[str, Any]) -> tuple[Any, ...]:
    """The generated identity columns; the store's real identity."""
    derived = derived_columns(body)
    return tuple(derived[name] for name in ("source_kind", "source_id", "content_sha256",
                                            "extraction_method", "extractor",
                                            "extractor_version"))


def identity_key(body: Mapping[str, Any]) -> str:
    """The application-level key; a convenience derived from the same identity."""
    return receipt.identity_key(list(body.get("processing_identity") or []))


def typed_row(action: Mapping[str, Any]) -> dict[str, Any]:
    """Map one terminal action to its single-column insert, or refuse."""
    if not isinstance(action, Mapping):
        raise StoreRefused("an action must be an object")
    if action.get("terminal") != "append":
        raise StoreRefused(f"only an append action maps to a stored row, not "
                           f"{action.get('terminal')!r}")
    body = action.get("receipt")
    if not isinstance(body, Mapping):
        raise StoreRefused("an append action must carry its canonical receipt")
    problems = receipt.validate_receipt(body)
    if problems:
        raise StoreRefused(f"the receipt body to store is invalid: {problems[:3]}")
    if receipt.receipt_digest(body) != action.get("digest"):
        raise StoreRefused("the action digest and the receipt body disagree")
    if identity_key(body) != action.get("identity_key"):
        raise StoreRefused("the action identity key and the receipt identity disagree")
    return {"receipt_body": json.loads(json.dumps(body, sort_keys=True, default=str))}


def row_problems(row: Mapping[str, Any]) -> list[str]:
    """Refuse any insert that supplies more than the canonical body, or a bad body."""
    if not isinstance(row, Mapping):
        return ["a row must be an object"]
    problems: list[str] = []
    extra = sorted(set(row) - set(WRITER_SUPPLIED_COLUMNS))
    if extra:
        problems.append(f"only {list(WRITER_SUPPLIED_COLUMNS)} may be supplied; "
                        f"unexpected columns {extra}")
    body = row.get(WRITER_SUPPLIED_COLUMNS[0])
    if not isinstance(body, Mapping):
        return problems + ["receipt_body must be an object"]
    problems.extend(receipt.validate_receipt(body))
    derived = derived_columns(body)
    if derived["receipt_digest"] != body.get("digest"):
        problems.append("the derived digest column would contradict the body")
    for name in ("extractor", "source_kind"):
        if derived[name] is not None and name == "extractor" \
                and derived[name] not in schema.EXTRACTORS:
            problems.append("the derived extractor would not be registered")
    if derived["status"] is not None and derived["status"] not in schema.STATUSES:
        problems.append("the derived status would not be registered")
    return problems


def _state_of(row: Mapping[str, Any]) -> dict[str, Any]:
    if isinstance(row.get(WRITER_SUPPLIED_COLUMNS[0]), Mapping):
        derived = derived_columns(row[WRITER_SUPPLIED_COLUMNS[0]])
    else:
        derived = dict(row)
    return {"identity": identity_components_from_derived(derived),
            "receipt_digest": str(derived.get("receipt_digest")),
            "status": derived.get("status"),
            "recorded_at": str(derived.get("recorded_at")),
            "recorded_at_sort_key": derived.get("recorded_at_sort_key")}


def identity_components_from_derived(derived: Mapping[str, Any]) -> tuple[Any, ...]:
    return tuple(derived.get(name) for name in ("source_kind", "source_id", "content_sha256",
                                                "extraction_method", "extractor",
                                                "extractor_version"))


def current_state(rows: Sequence[Mapping[str, Any]]) -> dict[str, Any]:
    """Derive one current state per identity; equal-instant disagreement is a conflict."""
    grouped: dict[tuple[Any, ...], list[dict[str, Any]]] = {}
    for row in rows:
        state = _state_of(row)
        grouped.setdefault(state["identity"], []).append(state)
    current: dict[tuple[Any, ...], dict[str, Any]] = {}
    conflicts: list[dict[str, Any]] = []
    for identity, entries in sorted(grouped.items(), key=lambda item: str(item[0])):
        ordered = sorted(entries, key=lambda item: (item["recorded_at_sort_key"],
                                                     item["receipt_digest"]))
        latest = ordered[-1]["recorded_at_sort_key"]
        tied = [item for item in ordered if item["recorded_at_sort_key"] == latest]
        digests = sorted({item["receipt_digest"] for item in tied})
        if len(digests) > 1:
            conflicts.append({"identity": list(identity), "recorded_at": ordered[-1]["recorded_at"],
                              "digests": digests})
            current[identity] = {"status": CONFLICT_STATUS, "receipt_digest": None,
                                 "recorded_at": ordered[-1]["recorded_at"],
                                 "recorded_at_sort_key": latest}
        else:
            current[identity] = {"status": ordered[-1]["status"],
                                 "receipt_digest": ordered[-1]["receipt_digest"],
                                 "recorded_at": ordered[-1]["recorded_at"],
                                 "recorded_at_sort_key": latest}
    return {"current": current, "conflicts": conflicts,
            "identities": len(grouped), "rows": len(rows)}


def plan_appends(actions: Sequence[Mapping[str, Any]],
                 existing_rows: Sequence[Mapping[str, Any]] = ()) -> dict[str, Any]:
    """Decide exactly which inserts would happen, and refuse everything else."""
    state = current_state(existing_rows)
    index = {(state_entry["identity"], state_entry["receipt_digest"])
             for state_entry in (_state_of(row) for row in existing_rows)}
    counts: dict[str, int] = {}
    for action in actions:
        key = str(action.get("identity_key"))
        counts[key] = counts.get(key, 0) + 1
    rows: list[dict[str, Any]] = []
    replays: list[dict[str, Any]] = []
    conflicts: list[dict[str, Any]] = []
    refusals: list[dict[str, Any]] = []
    for action in actions:
        key = str(action.get("identity_key"))
        terminal = action.get("terminal")
        if counts.get(key, 0) > 1:
            refusals.append({"identity_key": key,
                             "reason": "more_than_one_action_per_identity"})
            continue
        if terminal == "replay":
            replays.append({"identity_key": key, "receipt_digest": action.get("digest")})
            continue
        if terminal in ("conflict", "refuse", "invalid"):
            conflicts.append({"identity_key": key, "terminal": terminal})
            continue
        try:
            row = typed_row(action)
        except StoreRefused as exc:
            refusals.append({"identity_key": key, "reason": str(exc)})
            continue
        problems = row_problems(row)
        if problems:
            refusals.append({"identity_key": key, "reason": problems[0]})
            continue
        body = row[WRITER_SUPPLIED_COLUMNS[0]]
        derived = derived_columns(body)
        identity = identity_components(body)
        stored = state["current"].get(identity)
        if isinstance(stored, Mapping) and stored.get("status") == CONFLICT_STATUS:
            conflicts.append({"identity_key": key, "reason": "unresolved_stored_conflict"})
            continue
        if (identity, str(derived["receipt_digest"])) in index:
            replays.append({"identity_key": key, "receipt_digest": derived["receipt_digest"]})
            continue
        if stored is not None:
            if derived["recorded_at_sort_key"] < stored.get("recorded_at_sort_key"):
                refusals.append({"identity_key": key, "reason": "older_than_stored_receipt"})
                continue
            if derived["recorded_at_sort_key"] == stored.get("recorded_at_sort_key"):
                conflicts.append({"identity_key": key,
                                  "reason": "arrival_disagrees_with_stored_at_same_instant"})
                continue
        rows.append(row)
        index.add((identity, str(derived["receipt_digest"])))
        state["current"][identity] = {"status": derived["status"],
                                      "receipt_digest": derived["receipt_digest"],
                                      "recorded_at": str(derived["recorded_at"]),
                                      "recorded_at_sort_key": derived["recorded_at_sort_key"]}
    accounted = len(rows) + len(replays) + len(conflicts) + len(refusals)
    return {"rows": rows, "insert_count": len(rows), "replays": replays,
            "conflicts": conflicts, "refusals": refusals, "accounted": accounted,
            "reconciles": accounted == len(actions),
            "data_operations_proposed": 0}
