#!/usr/bin/env python3
"""``stage3_b3_span_schema.py`` — B3 evidence_spans DDL plan + a DISABLED apply runner.

THE TABLE.  ``evidence_spans`` stores byte-exact evidence regions, keyed on their identity so a
re-derivation is idempotent, with total lineage and an optional canonical agenda-item link.

THE RUNNER IS OFF.  ``ENABLED = False`` and a separate authorization token must BOTH be flipped
by a human before any write.  This module has never executed an apply, and the safe-work queue
that created it must not execute one.
"""

from __future__ import annotations

import hashlib
import json
from typing import Any, Mapping, Sequence

__all__ = ["AUTHORIZATION_TOKEN", "DISABLED_REASON", "ENABLED", "SCHEMA_PLAN_VERSION",
           "STATEMENTS", "STATEMENT_NAMES", "TABLE", "build_schema_plan", "canonical_sha256",
           "validate_schema_plan"]

SCHEMA_PLAN_VERSION = "kg-stage3-b3-span-store-schema/1.0"
TABLE = "evidence_spans"
DOCS = "supporting_documents"
ITEMS = "agenda_items"

#: Human-only gate.  Flipping ENABLED is not sufficient; the token must match too.
ENABLED = False
AUTHORIZATION_TOKEN = "B3-SPAN-STORE-APPLY-NOT-AUTHORIZED"
DISABLED_REASON = (
    "B3 span-store apply is disabled by design: it mutates the development database and "
    "requires an explicit human authorization, an exact plan path+digest and a fresh "
    "restore-verified backup receipt."
)

STATEMENT_NAMES = ("create_table", "unique_identity", "check_offsets", "check_kind",
                   "fk_documents", "fk_agenda_items", "index_agenda_item")

STATEMENTS: list[str] = [
    f"""CREATE TABLE {TABLE} (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supporting_doc_id integer NOT NULL,
    span_kind varchar(32) NOT NULL,
    text_offset_start integer NOT NULL,
    text_offset_end integer NOT NULL,
    span_sha256 char(64) NOT NULL,
    agenda_item_db_id integer NULL,
    link_status varchar(16) NOT NULL,
    lineage_source varchar(32) NOT NULL,
    lineage_parent_id integer NOT NULL,
    span_preview varchar(80) NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now()
)""",
    f"ALTER TABLE {TABLE} ADD CONSTRAINT uq_{TABLE}_identity UNIQUE "
    f"(supporting_doc_id, span_kind, text_offset_start, text_offset_end)",
    f"ALTER TABLE {TABLE} ADD CONSTRAINT ck_{TABLE}_offsets CHECK "
    f"(text_offset_start >= 0 AND text_offset_end > text_offset_start)",
    f"ALTER TABLE {TABLE} ADD CONSTRAINT ck_{TABLE}_kind CHECK "
    f"(span_kind IN ('stage1_meeting_event', 'stage3_result_item'))",
    f"ALTER TABLE {TABLE} ADD CONSTRAINT fk_{TABLE}_document FOREIGN KEY (supporting_doc_id) "
    f"REFERENCES {DOCS}(id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED",
    f"ALTER TABLE {TABLE} ADD CONSTRAINT fk_{TABLE}_agenda_item FOREIGN KEY (agenda_item_db_id) "
    f"REFERENCES {ITEMS}(id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED",
    f"CREATE INDEX ix_{TABLE}_agenda_item_db_id ON {TABLE} (agenda_item_db_id)",
]


def canonical_sha256(payload: Any) -> str:
    return hashlib.sha256(
        json.dumps(payload, sort_keys=True, separators=(",", ":"), default=str)
        .encode("utf-8")).hexdigest()


def build_schema_plan(*, created_at: str, target: Mapping[str, Any],
                      code_hashes: Mapping[str, str],
                      current_present: Sequence[str] = ()) -> dict[str, Any]:
    plan = {
        "kind": "kg-stage3-b3-span-store-schema-plan", "version": SCHEMA_PLAN_VERSION,
        "created_at": created_at, "mode": "dry-run", "applied": False, "enabled": False,
        "write_path": "absent by design",
        "target": dict(target),
        "producer": {"module": "scripts/kg/stage3_b3_span_schema.py",
                     "version": SCHEMA_PLAN_VERSION, "code_hashes": dict(code_hashes)},
        "table": TABLE,
        "statement_names": list(STATEMENT_NAMES),
        "statements": list(STATEMENTS),
        "statement_count": len(STATEMENTS),
        "writes_tables": 1,
        "current_present": sorted(current_present),
        "disable_reason": DISABLED_REASON,
    }
    plan["digest"] = canonical_sha256(plan)
    return plan


def validate_schema_plan(plan: Mapping[str, Any],
                         current_present: Sequence[str] = ()) -> list[str]:
    problems: list[str] = []
    if plan.get("applied") is not False:
        problems.append("a schema plan must never be marked applied")
    names = list(plan.get("statement_names") or [])
    if len(names) != len(plan.get("statements") or []):
        problems.append("statement_names and statements disagree in length")
    if set(names) != set(STATEMENT_NAMES):
        problems.append("statement_names do not match the declared statement set")
    if plan.get("statement_count") != len(STATEMENTS):
        problems.append("statement_count does not match the module's statement set")
    missing_code = not plan.get("producer", {}).get("code_hashes")
    if missing_code:
        problems.append("the plan binds no code hashes, so stale code could validate it")
    if plan.get("table") in set(current_present):
        problems.append(f"table {plan.get('table')!r} already exists in the target")
    if canonical_sha256({k: v for k, v in plan.items() if k != "digest"}) != plan.get("digest"):
        problems.append("the plan body does not recompute to its recorded digest")
    return problems


def apply_schema(*, plan: Mapping[str, Any], plan_path: str, plan_digest: str,
                 target: Mapping[str, Any], authorization_token: str | None = None,
                 approver: str | None = None, backup_receipt: Mapping[str, Any] | None = None,
                 connection: Any = None) -> dict[str, Any]:
    """REFUSES unless every gate is satisfied.  Deliberately does nothing while disabled."""
    if not ENABLED:
        return {"status": "refused", "reason": "runner_disabled", "wrote": 0,
                "detail": DISABLED_REASON}
    if authorization_token != AUTHORIZATION_TOKEN:
        return {"status": "refused", "reason": "missing_or_wrong_authorization_token",
                "wrote": 0}
    if not approver:
        return {"status": "refused", "reason": "no_named_human_approver", "wrote": 0}
    if not plan_path or not plan_digest:
        return {"status": "refused", "reason": "exact_plan_path_and_digest_required",
                "wrote": 0}
    if plan.get("digest") != plan_digest:
        return {"status": "refused", "reason": "plan_digest_mismatch", "wrote": 0}
    if not backup_receipt or not backup_receipt.get("restore_verified"):
        return {"status": "refused", "reason": "fresh_restore_verified_backup_required",
                "wrote": 0}
    problems = validate_schema_plan(plan)
    if problems:
        return {"status": "refused", "reason": "schema_plan_invalid", "problems": problems,
                "wrote": 0}
    if connection is None:
        return {"status": "refused", "reason": "no_connection_supplied", "wrote": 0}
    return {"status": "refused", "reason": "not_implemented_in_safe_queue", "wrote": 0}
